"""change to lower case

Revision ID: b3e2b21d3813
Revises: 
Create Date: 2019-04-29 12:00:06.622567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e2b21d3813'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('data_len', sa.Integer(), nullable=True),
    sa.Column('timestamp1', sa.Integer(), nullable=True),
    sa.Column('timestamp2', sa.Integer(), nullable=True),
    sa.Column('timesynctimestamp', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('seqno', sa.Integer(), nullable=True),
    sa.Column('hops', sa.Integer(), nullable=True),
    sa.Column('latency', sa.Integer(), nullable=True),
    sa.Column('data_len2', sa.Integer(), nullable=True),
    sa.Column('clock', sa.Integer(), nullable=True),
    sa.Column('timesynchtime', sa.Integer(), nullable=True),
    sa.Column('time_cpu', sa.Integer(), nullable=True),
    sa.Column('time_lpm', sa.Integer(), nullable=True),
    sa.Column('time_transmit', sa.Integer(), nullable=True),
    sa.Column('time_listen', sa.Integer(), nullable=True),
    sa.Column('best_neighbor', sa.Integer(), nullable=True),
    sa.Column('best_neighbor_etx', sa.Integer(), nullable=True),
    sa.Column('rtmetric', sa.Integer(), nullable=True),
    sa.Column('num_neighbors', sa.Integer(), nullable=True),
    sa.Column('beacon_interval', sa.Integer(), nullable=True),
    sa.Column('battery_voltage', sa.Integer(), nullable=True),
    sa.Column('battery_indicator', sa.Integer(), nullable=True),
    sa.Column('light1', sa.Integer(), nullable=True),
    sa.Column('light2', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('created_date')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('sensor')
    # ### end Alembic commands ###
